import clsx from 'clsx';
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './index.module.scss'
import { Package } from '../components/Package/Package';
import { packages } from '../components/Package/copy';
import { Whoami } from '../components/Whoami/Whoami';
import { Skills } from '../components/Skills/Skills';
import { Curve } from '../components/Curve/Curve';
import { FC } from 'react';
import { Packages } from '../components/Packages/Packages';
import { Projects } from '../components/Projects/Projects';
import { projects } from '../components/Project/copy';
import { posts } from '../components/Post/copy';
import { Posts } from '../components/Posts/Posts';
import { ContactMe } from '../components/ContactMe/ContactMe';

interface SectionProps {
  curve?: number;
  paddingBottom?: number;
  paddingTop?: number;
  className?: string;
};

const Section: FC<SectionProps> = (props) => {
  const {
    curve,
    children,
    paddingBottom,
    paddingTop,
    className,
  } = props;

  return (
    <section className={className}>
      {curve && (
        <Curve height={curve} />
      )}
      <div style={{
        paddingBottom: `${paddingBottom ?? 0}px`,
        paddingTop: `${paddingTop ?? 0}px`,
      }}>
        {children}
      </div>
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <div className={clsx(styles.page)}>
      <Head>
        <title>Hello world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Section
          paddingBottom={150}
          paddingTop={60}
          className={styles.whoamiSection}
        >
          <Whoami
            className={styles.whoami}
          />
        </Section>

        <Section
          curve={100}
          paddingBottom={190}
          paddingTop={90}
          className={styles.skillsSection}
        >
          <Skills
            className={styles.skills}
          />
        </Section>

        <Section
          curve={100}
          paddingBottom={190}
          paddingTop={90}
          className={styles.projectsSection}
        >
          <Projects
            className={styles.projects}
            projects={projects}
          />
        </Section>

        <Section
          curve={100}
          paddingBottom={190}
          paddingTop={90}
          className={styles.packagesSection}
        >
          <Packages
            className={styles.packages}
            packages={packages}
          />
        </Section>

        <Section
          curve={100}
          paddingBottom={190}
          paddingTop={90}
          className={styles.postsSection}
        >
          <Posts
            className={styles.posts}
            posts={posts}
          />
        </Section>

      
        <Section
          curve={100}
          paddingBottom={190}
          paddingTop={90}
          className={styles.contactMeSection}
        >
          <ContactMe />
        </Section>

      </main>
    </div>
  )
}

export default Home
